### PR TITLE
Add Rooch brand

### PR DESCRIPTION
**Pull request by geometryolife**
- [x] change the location to the `about` page
- [x] adding download buttons for each one
- [x] brand -> branding
- [x] add a link to the Rooch Brand Style Guideline
- [x] using `Image` for all pictures

### CODE REVIEW

**Comment by Mine77** [comment]
The entrance of this page should not be in the head bard.
Hidde the page and make an entrance on the About page.
Something like this:
image
----
And for each of the Logo file, add 2 download buttons, one for downloading SVG and another one for PNG.
You can refer to https://solana.com/branding
image

Also a button for downloading all files at once.
----
Name of the page should be branding, not brand 
----
In the branding page, add a link to the [Rooch Brand Style Guideline](https://www.figma.com/proto/9nb1ZKC3gghKGbUoNtBav1/Rooch-Brand-Style-Guide?type=design&node-id=18-3&scaling=contain&page-id=18%3A2)
Something like this:
```
Feel free to go through the [Rooch Brand Style Guideline](https://www.figma.com/proto/9nb1ZKC3gghKGbUoNtBav1/Rooch-Brand-Style-Guide?type=design&node-id=18-3&scaling=contain&page-id=18%3A2) before applying the Rooch branding.
```
use <Image> component provided by NextJS to increase the imaging loading speed.

**Comment by geometryolife** [comment]
可以帮忙看一下要怎么调整样式，让每个图片单独一行显示吗？我发现如果图片较小，会拼接到一起 @wow-sven @Mine77 不知道要怎么调了

**Comment by wow-sven** [comment]
> 可以帮忙看一下要怎么调整样式，让每个图片单独一行显示吗？我发现如果图片较小，会拼接到一起 @wow-sven @Mine77 不知道要怎么调了

I found a Chinese doc
https://tailwind.wyz.xyz/docs/width#header

ref https://github.com/wow-sven/rooch-network.github.io/tree/feature/brand
Retrofit based on your code， recommended to put the image configuration into pages/brand
image


Proposal
add components/pages  Store custom pages
add components/logos Svg

**Comment by geometryolife** [comment]
下载所有logo的那个必须要打包一个zip文件吗？ @wow-sven

**Comment by wow-sven** [comment]
> 下载所有logo的那个必须要打包一个zip文件吗？ @wow-sven

这样最简单，最简单的实现错误最少

**Comment by geometryolife** [comment]
@wow-sven 我还遇到一个小问题，不知道为什么黑色的logo会重复显示一遍

**Comment by Mine77** [comment]
logo 都用 css 加个底色吧，不然有些都看不到

**Comment by geometryolife** [comment]
Close this PR, #185 implements this feature better.

**Pull request closed without merging**
