### PR TITLE
add blog filter

### PR DESCRIPTION
**Pull request by wow-sven**

### CODE REVIEW

**Review by geometryolife — COMMENTED** [review]
we can directly ref the GitHub png will be better than adding author png.

**Comment by wow-sven** [comment]
> we can directly ref the GitHub png will be better than adding author png.

Maybe, If you don't think about firewalls

**Comment by geometryolife** [comment]
What do you think? @Mine77

**Comment by wow-sven** [comment]
> What do you think? @Mine77
Moving to https://github.com/rooch-network/rooch-network.github.io/issues/106, I want to merge this pr

**Pull request merged**
